-- ============================================================
-- Hub Master - Schema Unificado (Todos os bancos)
-- Adiciona tabelas de subscriptions e favorites ao PostgreSQL
-- ============================================================

-- ============================================================
-- Tabela: subscriptions (migrado do SQLite do subscription-api)
-- ============================================================
CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price REAL NOT NULL,
    currency TEXT DEFAULT 'BRL',
    billing_cycle TEXT DEFAULT 'monthly',
    renewal_date TEXT NOT NULL,
    category TEXT DEFAULT 'other',
    color TEXT DEFAULT '#6366f1',
    icon TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT true,
    notes TEXT DEFAULT '',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- Tabela: favorites (migrado do arquivo txt do favoritos)
-- ============================================================
CREATE TABLE IF NOT EXISTS favorites (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_favorites_name ON favorites(name);
CREATE INDEX IF NOT EXISTS idx_favorites_url ON favorites(url);

-- ============================================================
-- Importar dados do arquivo favorites.txt
-- ============================================================
INSERT INTO favorites (name, url) VALUES ('Gmail', 'https://mail.google.com/mail/u/0/h') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Google Alerts - Envia alerta de noticias pelo email', 'https://www.google.com.br/alerts') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Google Trends - Coisas mais pesquisadas no momento', 'https://trends.google.com.br/trends/?geo=BR') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Google Feud - Jogo', 'https://www.html-et-caetera.com/google-feud/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('What''s Came First? - Jogo', 'https://artsandculture.google.com/experiment/what-came-first/ZQGBUPErEE3bVg') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Rápido, desenhe! -Jogo', 'https://quickdraw.withgoogle.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DALL-E mini - Gerador de imagem', 'https://www.craiyon.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Site confiável', 'https://www.siteconfiavel.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Chess.com - Jogo', 'https://www.chess.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lichess - Jogo', 'https://lichess.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Artigo - Jogo', 'https://artigo.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Geoguessr - Jogo', 'http://www.geoguessr.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Yandex Imagens - Melhor buscados de imagens', 'https://yandex.com/images/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lampions Bet - Site de apostas', 'https://www.lampions.bet/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('SteamDB - Promoção de jogos', 'https://steamdb.info/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Fast - Teste de velocidade da internet', 'https://fast.com/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Virus Total - Checar arquivos', 'https://www.virustotal.com/gui/home/upload') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Let''s Enhance - Upscaler de imagens', 'https://letsenhance.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DreamStudio - Gerador de imagem', 'https://stabilityai.us.auth0.com/u/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Videoder - App de baixar videos', 'https://www.videoder.com/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Extrator de Imagens - Baixar todas imagens de um site', 'https://pt.rakko.tools/tools/56/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Bitly 0 Encurtador de URL', 'https://bityli.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('BotoStore - Melhores bots', 'https://botostore.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Just Delete Me - Como deletar contas de diversos sites', 'https://backgroundchecks.org/justdeleteme/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Wayback Machine - Arquivos de sites', 'https://web.archive.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Deepl Translator - Melhor tradutor', 'https://www.deepl.com/pt-BR/translator') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hunter - Procurar emails de empresas', 'https://hunter.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dólar Hoje - Cotação do dolar', 'https://dolarhoje.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Globe - Jogo', 'https://globle-game.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Letreco - Jogo', 'https://www.gabtoschi.com/letreco/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Contexto - Jogo', 'https://contexto.me/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pgsharp - Hack Pokemon GO', 'https://www.pgsharp.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Termo - Jogo', 'https://term.ooo/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ipogo - Hack Pokemon GO', 'https://ipogo.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Wikirota - Calcular distância e custos de viagem', 'https://www.wikirota.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Taggo - Meu cartão virtual', 'https://taggo.one/aleksandroalves') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stripchat', 'https://pt.stripchat.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Copy AI - AI para criar copy', 'https://app.copy.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Palavra do dia - Jogo', 'https://palavra-do-dia.pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Eternal Box - IA que transforma uma musica infinita', 'https://eternalbox.dev/jukebox_index.html') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Blaze IPTV', 'http://blaze.koffice.site/login/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Loja Blaze', 'https://www.lojablaze.online/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('FakeYou - Sintetizador de voz', 'https://fakeyou.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Palavres', 'https://palavr.es/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Moviedle', 'https://likewisetv.com/arcade/moviedle') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Posterdle', 'https://likewisetv.com/arcade/posterdle') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Doctranslator', 'https://www.onlinedoctranslator.com/pt/translationform') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gerador de Gmail', 'https://generator.email/blog/gmail-generator') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gerador de Gmail 2', 'https://tools.electronicbub.com/pt/gerador-de-e-mail-do-gmail/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pré-pós SEO', 'https://www.prepostseo.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('TokBoard', 'https://tokboard.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Picwish', 'https://picwish.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Trendingtopics', 'https://trendingtopics.com.br/brasil#') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Fuso Horario Mundial', 'https://fusohorariomundial.com.br/tabela') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('PVPOKE', 'https://pt-br.pvpoke-re.com/battle/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pogo Stat', 'https://pogostat.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('IMG2GO', 'https://www.img2go.com/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('MidJourney', 'https://www.midjourney.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Playground AI', 'https://playgroundai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mage Space', 'https://www.mage.space/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('CLIP Interrogator', 'https://huggingface.co/spaces/pharma/CLIP-Interrogator') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pxhere', 'https://pxhere.com/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stable Diffusion Prompt Generator', 'https://huggingface.co/spaces/Gustavosta/MagicPrompt-Stable-Diffusion') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tempmail', 'https://temp-mail.org/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Photopea', 'https://www.photopea.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Buscapé', 'https://www.buscape.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Copy Google Drive', 'https://script.google.com/macros/s/AKfycbxbGNGajrxv-HbX2sVY2OTu7yj9VvxlOMOeQblZFuq7rYm7uyo/exec') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Investing', 'https://br.investing.com/equities/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Passei Direto', 'https://www.passeidireto.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('GGMax', 'https://ggmax.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ulist', 'https://guihkx.github.io/ulist/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('MyFonts', 'https://www.myfonts.com/pages/whatthefont') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Whatfontis', 'https://www.whatfontis.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Extract', 'https://extract.me/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Toffee Share', 'https://toffeeshare.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Yandex Images', 'https://yandex.com/images/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tome', 'https://beta.tome.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Speed test Cloudflare', 'https://speed.cloudflare.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Visualizador De Imagens', 'https://andersonmak.com/scripts/visualizador-imagens.html') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Birme Redimensionar imagem', 'https://www.birme.net/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Emailondeck', 'https://www.emailondeck.com/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pixabay', 'https://pixabay.com/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Upscale', 'https://www.upscale.media/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Imgupscaler', 'https://imgupscaler.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pexels', 'https://www.pexels.com/pt-br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Smart Upscaler', 'https://icons8.com.br/upscaler') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Maximum Diffusion', 'https://huggingface.co/spaces/Nickhilearla135095/maximum_diffusion') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Upscaler', 'https://www.upscale.media/pt/upload') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Watermark Remover', 'https://www.watermarkremover.io/pt/upload') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Remover Fundo', 'https://www.erase.bg/pt/upload') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Restaurar Face', 'https://arc.tencent.com/en/ai-demos/faceRestoration') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Jogos Online', 'https://poki.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tempmailo', 'https://tempmailo.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mail Temp', 'https://mail.tm/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Wetransfer', 'https://wetransfer.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('ChatSonic', 'https://app.writesonic.com/pt-pt/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Download Imagens', 'https://products.aspose.app/html/pt/image-downloader') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ytscribe', 'https://ytscribe.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stable Diffusion Colab', 'https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_v2_webui_colab.ipynb') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Magic Eraser', 'https://magicstudio.com/magiceraser') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stable Diffusion 2 - Colab', 'https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable_diffusion_1_5_webui_colab.ipynb') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Reference Pictures', 'https://reference.pictures/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Unsplash', 'https://unsplash.com/pt-br') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Remove BG', 'https://www.remove.bg/pt-br') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Instant Username', 'https://instantusername.com/#/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lufi Upload', 'https://upload.disroot.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Civit AI', 'https://civitai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('SD 1111', 'https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=Y9EBc437WDOs') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pirate Bay', 'https://pirate-bays.net/torrent-search') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('BT Met Utorrent', 'https://btmet.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Btdig', 'https://btdig.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('PromptHero', 'https://prompthero.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Umbler Email', 'https://mail.umbler.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Meu Pastebin', 'https://pastebin.com/u/aajunior43') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('YouTube Scribe', 'https://ytscribe.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Chatsonic', 'https://app.writesonic.com/pt-pt/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mail Temp', 'https://mail.tm/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('GPT Zero', 'https://gptzero.me/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompt Hunt', 'https://www.prompthunt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Wonder Dynamics', 'https://app.wonderdynamics.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Open Art', 'https://openart.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Cat Bird AI', 'https://www.catbird.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Midjourney Showcase', 'https://www.midjourney.com/showcase/recent/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Getimg', 'https://getimg.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('´Prodia Ai', 'https://app.prodia.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Futurepedia', 'https://www.futurepedia.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DreamStudio', 'https://dreamstudio.ai/generate') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Graviti', 'https://webui.graviti.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Copy Generator', 'https://app.copygenerator.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AgentGPT', 'https://agentgpt.reworkd.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Picso', 'https://picso.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Character AI', 'https://beta.character.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Open Assistant', 'https://open-assistant.io/chat') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Colab55', 'https://www.colab55.com/me') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Seek Art', 'https://seek.art/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Future Tools', 'https://www.futuretools.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Plazmapunk', 'https://www.plazmapunk.com/app') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AICA', 'https://aica.vercel.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('RunDiffusion', 'https://app.rundiffusion.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Replicate', 'https://replicate.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('God Mode', 'https://godmode.space/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Cri.ai Prompts', 'https://prompt.criai.net.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('CLIP Interrogator', 'https://huggingface.co/spaces/pharma/CLIP-Interrogator') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Perplexity', 'https://www.perplexity.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gigapixel AI', 'https://www.topazlabs.com/gigapixel-ai') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Clipdrop Relight', 'https://clipdrop.co/relight') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pixelbin IO', 'https://console.pixelbin.io/organization/292159/dashboard') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mlabs', 'https://accounts.mlabs.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Leonardo AI', 'https://app.leonardo.ai/auth/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Kaiber', 'https://www.kaiber.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mage Space', 'https://www.mage.space/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Playground AI', 'https://playgroundai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Getimg AI', 'https://getimg.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dream Like', 'https://dreamlike.art/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dream Studio', 'https://beta.dreamstudio.ai/generate') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Magic Prompt', 'https://huggingface.co/spaces/Gustavosta/MagicPrompt-Stable-Diffusion') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Leia PIX', 'https://convert.leiapix.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('You', 'https://you.com/search?q=who+are+you&tbm=youchat&cfr=chat') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Witeboard', 'https://witeboard.com/028e2350-df0a-11ed-b429-73a650fc22c7') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Kleki', 'https://kleki.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Coolors', 'https://coolors.co/palettes/trending') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pelando', 'https://www.pelando.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Alternative', 'https://alternativeto.net/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Nperf', 'https://www.nperf.com/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Leonardo AI', 'https://app.leonardo.ai/ai-generations') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Picfinder', 'https://picfinder.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Instant Art', 'https://instantart.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Blaze IPTV', 'https://blaze.koffice.site/login/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Check list Pokémon GO', 'https://9db.jp/pokemongo/data/6406') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Check list Pokémon GO II', 'https://leekduck.com/shiny/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ihit', 'https://ihit.com.br/loja/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adobe Enhancer', 'https://podcast.adobe.com/enhance') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Taggo One', 'https://taggo.one/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lexica', 'https://lexica.art/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Reference Picture', 'https://reference.pictures/figure-drawing-rachel/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Color Adobe', 'https://color.adobe.com/pt/create/color-wheel') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Kaiber', 'https://app.kaiber.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Site Confiável', 'https://www.siteconfiavel.com.br/site/promptstacks-com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Check list Pokémon GO III', 'https://rplus.github.io/Pokemon-shiny/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('PNG Tree', 'https://pt.pngtree.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Caractere Invisível', 'https://fabricioventura.com/caractere') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Archive ORG', 'https://web.archive.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pastebin', 'https://pastebin.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Seedr', 'https://www.seedr.cc/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Envato elements', 'https://elements.envato.com/pt-br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('The Pirate Bay', 'https://pirate-bays.net/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Cursos Top', 'https://downloadcursos.top/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Geforce Now', 'https://abya.com/gfn/pt-BR') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Vector Magic', 'https://pt.vectormagic.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Color Hunt', 'https://colorhunt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ferramentas', 'https://www.negociosemmente.com.br/ferramentas') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompt Base', 'https://promptbase.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('D-ID', 'https://studio.d-id.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompts GPT Pago', 'https://comprechat.circle.so/c/inicie-aqui') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompts GPT Pago II', 'https://ideiaschatgpt.com.br/prompts/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Estilos Midjourney', 'https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/blob/main/README.md') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Remover marca d''água de video', 'https://online-video-cutter.com/pt/remove-logo') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Estilos Midjourney', 'https://www.midlibrary.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Varias ferramentas Premium em uma só', 'https://tuconjunta.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('10 Min email temporário', 'https://10minemail.com/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompts pagos GPT', 'https://chatgpt-lucrativo.notion.site/chatgpt-lucrativo/Marketing-Copie-e-Cole-500-Comandos-Secretos-para-ChatGPT-99-prompts-para-otimizar-tarefas-9faaa2f9fb5f45bea41f7c763917ce23') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Designi', 'https://www.designi.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Freepik', 'https://br.freepik.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompts pagos GPT', 'https://comprechat.circle.so/c/diversos/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Vectorizer IO', 'https://www.vectorizer.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('IMI Prompt', 'https://www.imiprompt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Essa pessoa não existe', 'https://this-person-does-not-exist.com/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Future Lab', 'https://www.futureailab.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('GPT Open Source', 'https://chat.lmsys.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AI Fusion', 'https://aifusionapp.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adobe Animate', 'https://express.adobe.com/express-apps/animate-from-audio/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stadio AI', 'https://stadio.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dream Like', 'https://dreamlike.art/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Run Diffusion', 'https://app.rundiffusion.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Plasma Punk', 'https://www.plazmapunk.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('ART Station', 'https://www.artstation.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Estilos Midjourney', 'https://rentry.org/artists_sd-v1-4_iv') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Microsoft Designer', 'https://designer.microsoft.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Open Assistent GPT', 'https://open-assistant.io/pt-BR/chat/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Scenario', 'https://app.scenario.com/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pixai Art', 'https://pixai.art/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Discord', 'https://discord.com/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prodia IA', 'https://app.prodia.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Graviti', 'https://webui.graviti.com/?__theme=dark') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('InvokeAI Colab', 'https://colab.research.google.com/github/peaashmeter/invoke-ai-gui-colab/blob/main/invoke_ai_gui_colab.ipynb') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Camenduru', 'https://github.com/camenduru/stable-diffusion-webui-colab') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Nightcafe', 'https://nightcafe.studio/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DreamBooth', 'https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Wirestock - Vender imagens em varios banco de imagens de uma vez', 'https://wirestock.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pimeyes - Buscador de rostos na internet', 'https://pimeyes.com/en') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hero - Varios prompts para chatGPT', 'https://hero.page/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AItools - Varias ferramentas de IA', 'https://aitools.lol/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gumroad - Vender produtos digitais', 'https://app.gumroad.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Library - Varias ferramentas de IA', 'https://library.phygital.plus/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AutoGPT', 'https://autogpt.thesamur.ai/agi') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('CamelAGI', 'https://camelagi.thesamur.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Alternativa do Chat GPT', 'https://chatbot.theb.ai/#/chat/1002') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('GFPGAN - Upscale de imagens no google colab', 'https://colab.research.google.com/drive/1k2Zod6kSHEvraybHl50Lys0LerhyTMCo?usp=sharing') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Copy Folder - Transferir arquivos compartilhados para o Google Drive', 'https://workspacetips.io/tools/copy-folder/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornpen AI - PN', 'https://pornpen.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Made Porn - PN', 'https://made.porn') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AI Hentai - PN', 'https://ai-hentai.net') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornpen Art - PN', 'https://pornpen.art') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('AI Pornjourney - PN', 'https://aipornjourney.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Deviantart', 'https://www.deviantart.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adobe Firefly', 'https://firefly.adobe.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Artstation', 'https://www.artstation.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hotpot AI', 'https://hotpot.ai/art-generator') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Face Restoration - IA restaurar face', 'https://arc.tencent.com/en/ai-demos/faceRestoration') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('ESRGAN - Upscaler', 'https://replicate.com/xinntao/realesrgan') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Convert DPI - Converter imagens para Banco de imagens', 'https://convert-dpi.com/br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Calculadora de regra de 3', 'https://www.4devs.com.br/calculadora_regra_tres_simples') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Bing Creator - IA de criar imagem', 'https://www.bing.com/images/create') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adobe Firefly - IA', 'https://firefly.adobe.com/generate') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('CRIAI - Ferramenta de gerar prompts de Imagem', 'https://prompt.criai.net.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Sinkin AI', 'https://sinkin.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Patience. AI', 'https://www.patience.ai') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Snack Prompt - Rede social de prompts para GPT', 'https://snackprompt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Eleven Labs - Ia Sintetiza texto e clona voz', 'https://beta.elevenlabs.io') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Theresanaiforthat - Biblioteca de IAS', 'https://theresanaiforthat.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompt Vibes - Biblioteca de Prompts', 'https://www.promptvibes.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('MidJourney-Styles-and-Keywords-Reference', 'https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Chatabc', 'https://aajunior43.chatabc.ai') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('PIC Enhancer - Upscale', 'https://picsenhancer.com/upload') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Phygital - Varias ferramentas SD', 'https://app.phygital.plus/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Aitech Viral - Biblioteca de IA', 'https://aitechviral.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Onlyfans ai', 'https://onlyfansai.net/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Heuristica', 'https://www.heuristi.ca/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Promptden', 'https://promptden.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Runpod', 'https://runpod.io') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Arthub', 'https://arthub.ai') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Artifylabs', 'https://artifylabs.io/restore') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('FlowGPT', 'https://flowgpt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornderful', 'https://pornderful.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornjoy', 'https://pornjoy.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Onlyfakes', 'https://onlyfakes.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornshow', 'https://pornshow.ai/home') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hero', 'https://hero.page/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Etsy - Comprer e vender Prompts', 'https://www.etsy.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('SCISPACE - IA para estudos cientificos', 'https://typeset.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Seaart AI - Gerar imagens', 'https://www.seaart.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('ChatPDF - ChaatGPT para PDF', 'https://www.chatpdf.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('cohesive', 'https://cohesive.so/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Calculadora de AR', 'https://calculateaspectratio.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Umbler - Email', 'https://mail.umbler.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Heygen', 'https://www.heygen.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Flowgpt', 'https://flowgpt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DR. Far Far', 'https://www.dr-farfar.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Addmefast - Trocar seguidores', 'https://addmefast.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Woxo - Ia de criar vídeo', 'https://woxo.tech/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Fornecedor do Brasil - Painel de seguidores', 'https://fornecedorbrasil.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Turbo Leads - Comprar contas para extração', 'https://turboleads.mycartpanda.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Matconte - Bots top para telegram', 'https://matheusconte.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('SMS Virtual - Comprar chip', 'https://smsvirtual.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('ZapCloud - Disparos em massa', 'https://zapcloud.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Maya IA', 'https://www.mayaai.net/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Thinkdiffusion', 'https://www.thinkdiffusion.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Scribd Downloader - Baixar arquivos do Scribd', 'https://docdownloader.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Imgnai', 'https://app.imgnai.com/generate') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Archive', 'https://archive.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ifind - Consulta ilegal', 'https://i-find.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Uploud de PDF para o GPT ler', 'https://aipdf.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Vercel - Hospedar repositório do Github', 'https://vercel.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Unicórnio Shop - Comprar contas premium', 'https://unicornshop.cc/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('HG Store 98 - Loja de uniforme de futebol', 'https://hgstore98.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pronto Mail - E-mail criptografado', 'https://mail.proton.me/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hispy - Ferramenta de espionagem', 'https://www.hispy.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Exploit DB - Termos de Google Dorks', 'https://www.exploit-db.com/google-hacking-database') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Voice Clone - Dankicode', 'https://voiceclone.dankicode.ai/login.php') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adarsus - Remover metadados', 'https://www.adarsus.com/en/remove-metadata-online-document-image-video') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Egirls - Onlyfans criados por IA', 'https://egirls.wtf/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Painel Blaze IPTV - novo', 'https://painel.blaze.tv.br/index.php') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('POE - Várias IAs', 'https://poe.com/chat/2nkam00wubbc92bnuz8') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Face Swapper', 'https://faceswapper.ai/swapper') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('LensGO AI', 'https://lensgo.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Estica - Loja para vender camisetas', 'https://estica.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dólar Hoje', 'https://dolarhoje.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ideogram AI', 'https://ideogram.ai/t/trending') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('G Prompter - Gerar Prompts', 'https://www.g-prompter.com/en/prompt/photo') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Heylink - Árvore de link', 'https://heylink.me/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Vibx - Comprar e vender pelo telegram', 'https://www.marketplace.vibx.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('PI IA', 'https://pi.ai/talk') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dispara Ai - Enviar mensagem em massa', 'https://app.dispara.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('GOVIP - Ótimo site para Designer', 'https://govip.com.br/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('PasteFo', 'https://paste.fo/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Porn Store', 'https://pornstore.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('User Drive - Upload', 'https://usersdrive.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dditor de imagem com IA', 'https://avc.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Placeit - Mockups Online', 'https://placeit.net/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Modyfy IA', 'https://www.modyfi.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Simples Scrapre GPT', 'https://simplescraper.io/scrapetoai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Topai - Melhores IAs', 'https://topai.tools/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Agenda Hero - Adiciona seus afazeres no Google Agenda', 'https://agendahero.com/magic?utm_source=topai.tools&utm_medium=website_topai&utm_campaign=topai.tools') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Kreai', 'https://www.krea.ai/home') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Palavras Chave', 'https://keywordsheeter.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DPI de imagens', 'https://convert-dpi.com/br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Nbox Ai - Varias LLMs', 'https://chat.nbox.ai') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Educafit - Curso de educação física', 'https://educafit.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('ChatGOT', 'https://start.chatgot.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Theb Ai', 'https://beta.theb.ai/home') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Cg Dream', 'https://cgdream.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pandora Box', 'https://www.pandorasbox.ai/nsfw') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Product Hunt', 'https://www.producthunt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pixio', 'https://pixio.myapps.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mylens', 'https://mylens.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Squaad Ai', 'https://squaadai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Guinness', 'https://www.guinnessworldrecords.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Download videos Youtube', 'https://www.downloadbazar.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('TTS Openai', 'https://huggingface.co/spaces/ysharma/OpenAI_TTS_New') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Suno AI', 'https://www.suno.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Midjourney Stats', 'https://midjourneystats.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Aitoptools', 'https://aitoptools.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Producthunt', 'https://www.producthunt.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Shakker ai', 'https://www.shakker.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Glif', 'https://glif.app/glifs') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Claude AI', 'https://claude.ai/chats') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pikaso', 'https://www.freepik.com/pikaso') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Estante virtual', 'https://www.estantevirtual.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Biblioteca PN', 'https://www.tblop.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompt Midjourney', 'https://artificin.com/prompt-builder') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Grupos discord', 'https://disboard.org/pt-pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Erome PN', 'https://www.erome.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Papelaria Unicornio', 'https://papelariaunicornio.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Traduzir PDF', 'https://translate.google.com/?sl=en&tl=pt&op=docs') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Love PDF', 'https://www.ilovepdf.com/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Portion', 'https://portions-b809c128e647.herokuapp.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Videohighlight', 'https://videohighlight.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Programiz', 'https://www.programiz.com/html/online-compiler/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Jornal o regional', 'https://www2.oregionaljornal.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Typingmind', 'https://www.typingmind.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gpte', 'https://gpte.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Loja PN vibx', 'https://marketplace.vibx.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Baixar Scribd', 'https://scribd.vpdfs.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pocket', 'https://getpocket.com/pt/saves') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Extensão Top', 'https://fastforward.team/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Consensus', 'https://consensus.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Typeset', 'https://typeset.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Groq', 'https://groq.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Agents', 'https://agents.rolemodel.ai/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Criador de prompt', 'https://seu.design/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Docs estilo midjournet', 'https://docs.google.com/spreadsheets/u/0/d/1h6H2CqjLdZMbLjlz6EHwemfO4fkIzAfWtjRAMSa2KHE/htmlview?pli=1&utm') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompt Helper Midjourney', 'https://midjourney-prompt-helper.netlify.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Arthub', 'https://arthub.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Midjourney Style', 'https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/blob/main/Pages/MJ_V4/Style_Pages/Just_The_Style/Design_Styles.md') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tune Chat', 'https://chat.tune.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Biblioteca de GPTs', 'https://gptsdex.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stable diffusion CheatSheet', 'https://supagruen.github.io/StableDiffusion-CheatSheet/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mistral', 'https://auth.mistral.ai/ui/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Caça style', 'https://glif.app/@fab1an/glifs/clska7jpn002u132h3zjl0m9v') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Printwhatyoulike', 'https://www.printwhatyoulike.com/home/index') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Glbgpt', 'https://glbgpt.com/mChatGpt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Oksuro', 'https://oksuro.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gov assinatura eletronica', 'https://www.gov.br/governodigital/pt-br/identidade/assinatura-eletronica') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Apob', 'https://beta.apob.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('You IA', 'https://you.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Stylar', 'https://www.stylar.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Status Midjourney', 'https://status.midjourney.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompts Ideas', 'https://promptsideas.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Turbo Scribe AI', 'https://turboscribe.ai/dashboard') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Downdetector', 'https://downdetector.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('TopGG', 'https://top.gg/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Promptlibrary', 'https://promptlibrary.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Promeai', 'https://www.promeai.pro/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Reka', 'https://chat.reka.ai/auth/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lummi', 'https://www.lummi.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ytscribe', 'https://ytscribe.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Caractere invisível', 'https://fabricioventura.com/caractere?utm_source=pocket_saves') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Aistudio', 'https://aistudio.google.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mallow', 'https://mallow.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Udio', 'https://www.udio.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mymemo', 'https://app.mymemo.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Midgenai', 'https://www.midgenai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Recraft', 'https://www.recraft.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Breakerfollow', 'https://www.breakerfollow.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Zero-gpu-s', 'https://huggingface.co/spaces/enzostvs/zero-gpu-spaces?utm_source=pocket_saves') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Abacus AI', 'https://apps.abacus.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Status invest', 'https://statusinvest.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Investidor 10', 'https://investidor10.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Topinvest simulados', 'https://simulados.topinvest.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Whimsical', 'https://whimsical.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Markmap', 'https://markmap.js.org/repl') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Phind', 'https://www.phind.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Make', 'https://www.make.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Zapier', 'https://zapier.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Labs perplexity', 'https://labs.perplexity.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Git Mind', 'https://gitmind.com/pt/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lmsys Arena Chatbot', 'https://chat.lmsys.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Invideo AI', 'https://invideo.io/ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mapify', 'https://mapify.so/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tost', 'https://tost.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Role model', 'https://chat.rolemodel.ai/c/new') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Llama coder', 'https://llamacoder.together.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Giz AI', 'https://app.giz.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Openai TSS', 'https://platform.openai.com/playground/tts?utm_source=pocket_saves') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Style Midjourney', 'https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference?utm_source=pocket_shared') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pix Verse', 'https://app.pixverse.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Scribd download', 'https://scribd.vpdfs.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Similar sites', 'https://www.similarsites.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lovable', 'https://lovable.dev/login?redirect=%2Fprojects%2F95b6cf99-6386-4ef2-ae14-ed6598a55145') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Artflow', 'https://app.artflow.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Deepseek', 'https://chat.deepseek.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mistral', 'https://auth.mistral.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Liquid AI', 'https://playground.liquid.ai/login') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Inner AI', 'https://platform.innerai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Dzine', 'https://www.dzine.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Fliki', 'https://fliki.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Piclumen', 'https://www.piclumen.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Meta AI', 'https://www.meta.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Nvidia nemotron', 'https://build.nvidia.com/nvidia/llama-3_1-nemotron-70b-instruct?utm_source=pocket_saves') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Superporn', 'https://www.superporn.com/pornstars?') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tubepornstars', 'https://www.tubepornstars.com/pt-br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornstars', 'https://pornstars.tube/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hailuoai', 'https://hailuoai.video/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adapta', 'https://adapta.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Assoass', 'https://www.assoass.com/pt-br/category/anal') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Toppornsites', 'https://toppornsites.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Findtubes', 'https://www.findtubes.com/pt-br/category/anal') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Adobe - Comprimir PDF', 'https://www.adobe.com/br/acrobat/online/compress-pdf.html') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Promptperfect', 'https://promptperfect.jina.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hotshot', 'https://hotshot.co/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Profundo', 'https://www.profundo.app/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Gofretes', 'https://gofretes.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ai music', 'https://aimusic.so/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Freeflo', 'https://freeflo.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Prompter', 'https://prompter.fofr.a') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Felo AI', 'https://felo.ai/search') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Basedlabs', 'https://www.basedlabs.ai/generate') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Together AI', 'https://api.together.ai/signin') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Color IO', 'https://app.color.io/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('LM Arena', 'https://lmarena.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Notebook LM', 'https://notebooklm.google.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Name that pornstar', 'https://namethatpornstar.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Fap folder', 'https://fapfolder.club/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Telegra', 'https://telegra.ph/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('EGP TCE', 'https://egp.tce.pr.gov.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Instituto Federal do Rio Grande do Sul - Cursos', 'https://moodle.ifrs.edu.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Ttsopenai', 'https://ttsopenai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('TCE ENTIDADE', 'https://servicos.tce.pr.gov.br/tcepr/tribunal/relacon/Entidade') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('SENADO Cursos', 'https://saberes.senado.leg.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Websim', 'https://websim.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pornpics', 'https://www.pornpics.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Findtubes', 'https://www.findtubes.com/pt-br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Vidu', 'https://www.vidu.studio/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Lumalabs', 'https://lumalabs.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('arxiv', 'https://arxiv.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Pomodoro timer', 'https://app.pomodorotimer.online/pt') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('V0', 'https://v0.dev/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Tool finder', 'https://toolfinder.co/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Deep swapper', 'https://www.deepswapper.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Face swapper', 'https://faceswapper.ai') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Teradownloader', 'https://teradownloader.com') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Hailuoai', 'https://hailuoai.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Markdown to pdf', 'https://www.markdowntopdf.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Preciso imprimir', 'https://precisoimprimir.com.br/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Raidrive', 'https://www.raidrive.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Chatplayground', 'https://app.chatplayground.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Omnigpt', 'https://app.omnigpt.co/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Recraft', 'https://www.recraft.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Promptlibrary', 'https://promptlibrary.org/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Vizard', 'https://vizard.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Download Terabox', 'https://terabox.hnn.workers.dev/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('DNS Adguard', 'https://auth.adguard.com/login.html') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Poppop AI', 'https://poppop.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Komo AI', 'https://komo.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Promptsideas', 'https://promptsideas.com/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Mymemo', 'https://app.mymemo.ai/') ON CONFLICT DO NOTHING;
INSERT INTO favorites (name, url) VALUES ('Reka AI', 'https://chat.reka.ai/chat') ON CONFLICT DO NOTHING;